name: cli
description: A sample command-line application.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.1.0

dependencies:
  args: 2.4.2
  common:
    git:
      url: https://github.com/eugenechyrski/localsend.git
      path: common
  path: 1.9.0
  collection: ^1.17.2 # allow newer versions, so it can compile with newer Flutter versions

  uuid: 3.0.7
  shelf: 1.4.1
  shelf_router: 1.1.4
  basic_utils: 5.7.0
  dio: 5.4.1

  refena_inspector_client: 1.2.0
  dart_mappable: ^4.2.0
dev_dependencies:
  build_runner: ^2.4.8
  dart_mappable_builder: ^4.2.0
  lints: ^2.0.0
  test: ^1.21.0
